#!/usr/bin/env python3
#
# This file is part of turnkey-version
#
# turnkey-version is open source software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 3 of the
# License, or (at your option) any later version.

import argparse
import json
import os
import sys
from typing import NoReturn

import sysversion

TurnkeyVersionError = sysversion.TurnkeyVersionError


def fatal(msg: str) -> NoReturn:
    print(msg, file=sys.stderr)
    sys.exit(1)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="TurnKey Linux Version information",
    )

    # Version info source

    input_format = parser.add_argument_group(
        "Information source",
        description="Where turnkey-version reads the info from. Defaults to"
        " /etc/turnkey_version if no source set",
    )
    file_or_str = input_format.add_mutually_exclusive_group()
    # rootfs provides backwards compatability
    file_or_str.add_argument(
        "rootfs",
        type=str,
        metavar="ROOTFS",
        nargs="?",
        default=None,
        help="Path to rootfs. Reads ROOTFS/etc/turnkey_version",
    )
    file_or_str.add_argument(
        "-f",
        "--file",
        type=str,
        metavar="PATH_TO_FILE",
        default=None,
        help="Path to text file containing turnkey version string",
    )
    file_or_str.add_argument(
        "-s",
        "--string",
        type=str,
        metavar="TKL_VER_STR",
        default=None,
        help="TurnKey version string ('turnkey-' prefix optional)",
    )

    # Output information options
    info_options = parser.add_argument_group(
        "Information output options",
        description="If any of these options are given, output format will be"
        " space separated (default) or json; multiple elements will be ordered"
        " 'NAME VERSION CODENAME ARCH [DEBIAN_VERSION DEBIAN_ARCH]'",
    )
    info_options.add_argument(
        "-n",
        "--name",
        action="store_true",
        help="TurnKey app name - e.g. 'core'",
    )
    info_options.add_argument(
        "-t",
        "--tklversion",
        action="store_true",
        help="version number - e.g. '19.0'")
    info_options.add_argument(
        "-c",
        "--codename",
        action="store_true",
        help="Debian codename (from turnkey_version) - e.g. 'trixie'",
    )
    info_options.add_argument(
        "-r",
        "--arch",
        action="store_true",
        help="architechture (from turnkey_version) - e.g. 'amd64'",
    )
    info_options.add_argument(
        "-a",
        "--all",
        action="store_true",
        help="Space separated name, version, codename & arch (same as -ntcr)",
    )

    # Additional/alternate output information options
    additional_output = parser.add_argument_group(
        "Additional/alternate info",
        description="Return additional/alternate OS info. If TurnKey version"
        " specifc info is also desired, relevant 'Information output options'"
        " must be selected",
    )
    additional_output.add_argument(
        "-d",
        "--debian-codename",
        action="store_true",
        help="Debian codename (from system/chroot)",
    )
    additional_output.add_argument(
        "-A",
        "--debian-arch",
        action="store_true",
        help="Debian architecture (from system/chroot)"
    )

    # Output format
    output_format = parser.add_argument_group(
        "Output format",
        description="If no 'Information output options' are selected, -o"
        " (default) will be a '-' separated string with a 'turnkey-' prefix"
        " E.g. 'turnkey-core-19.0-trixie-amd64'; otherwise will be space"
        " separated",
    )
    output_format_options = output_format.add_mutually_exclusive_group()
    output_format_options.add_argument(
        "-j",
        "--json",
        action="store_true",
        help="output all values as json string - conflicts with other output"
        " options format options",
    )
    output_format.add_argument(
        "-o",
        "--output-string",
        action="store_true",
        default=None,
        help="output all values as a raw string (default)",
    )

    args = parser.parse_args()
    # TODO
    print(args)
    sys.exit(0)
    if args.name or args.tklversion or args.codename or args.arch:
        output_values = True
    else:
        output_values = False
    if args.all and output_values:
        parser.error(
            "-a|--all and -n|--name / -t|--tklversion / -c|--codename"
            " / -r|--arch are mutually exclusive.",
        )
    if args.json and (args.all or output_values):
        parser.error("-j|--json conflicts with other output values.")
    if args.string:
        print("STRING")
        turnkey_version = args.string
    else:
        try:
            turnkey_version = sysversion.read_file(
                rootfs=args.rootfs, file=args.file,
            )
        except TurnkeyVersionError as e:
            fatal(e)

        # ensure that args.file is relative to args.rootfs
        if args.file:
            rootfs = ""
            v_file = os.path.abspath(args.file)
        else:
            rootfs = args.rootfs
            v_file = _TKL_VER

        turnkey_version = sysversion.get_turnkey_version(rootfs, v_file)
    if not turnkey_version:
        fatal(
            "can't detect turnkey version - missing or invalid file"
            f"'{os.path.join(rootfs, v_file)}'",
        )

    tkl_appver = []
    tkl_appver_cls = sysversion.AppVer(turnkey_version, rootfs=rootfs)
    if args.all:
        args.name = True
        args.tklversion = True
        args.codename = True
        args.arch = True
    if args.name:
        tkl_appver.append(tkl_appver_cls.appname)
    if args.tklversion:
        tkl_appver.append(tkl_appver_cls.tklver)
    if args.codename:
        tkl_appver.append(tkl_appver_cls.codename)
    if args.arch:
        tkl_appver.append(tkl_appver_cls.arch)
    if args.debian_codename:
        tkl_appver.append(tkl_appver_cls.deb_codename)
    if args.json:
        print(
            json.dumps(
                tkl_appver_cls.app_json(deb_ver=args.debian_codename),
                indent=2,
            ),
        )
    elif tkl_appver:
        print(" ".join(tkl_appver))
    else:
        print(turnkey_version)


if __name__ == "__main__":
    main()
