#!/usr/bin/env python3
#
# This file is part of turnkey-version
#
# turnkey-version is open source software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 3 of the
# License, or (at your option) any later version.

import argparse
import json
import os
import sys
from typing import NoReturn

import sysversion

_ROOTFS = "/"
_TKL_VER = "etc/turnkey_version"
TurnkeyVersionError = sysversion.TurnkeyVersionError


def fatal(msg: str) -> NoReturn:
    print(msg, file=sys.stderr)
    sys.exit(1)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="TurnKey Linux Version information",
    )
    file_or_str = parser.add_mutually_exclusive_group()
    # rootfs provides backwards compatability
    file_or_str.add_argument(
        "rootfs",
        type=str,
        nargs="?",
        default=_ROOTFS,
        help="Path to root filesystem (default: / - reads ROOTFS/{_TKL_VER}.",
    )
    file_or_str.add_argument(
        "-f",
        "--file",
        type=str,
        metavar="PATH_TO_FILE",
        default=None,
        help="Path to text file containing turnkey version string.",
    )
    file_or_str.add_argument(
        "-s",
        "--string",
        type=str,
        metavar="TKL_VER_STR",
        help="turnkey version string('turnkey-' prefix optional).",
    )
    output = parser.add_argument_group(
        "Output options",
        description="Output format (space separated or json); multiple"
        " elements will be ordered 'NAME VERSION CODENAME ARCH'",
    )
    output.add_argument(
        "-n",
        "--name",
        action="store_true",
        help="TurnKey app name - e.g. 'core'",
    )
    output.add_argument(
        "-t",
        "--tklversion",
        action="store_true",
        help="version number - e.g. '19.0'")
    output.add_argument(
        "-c",
        "--codename",
        action="store_true",
        help="Debian codename (from turnkey_version) - e.g. 'trixie'",
    )
    output.add_argument(
        "-r",
        "--arch",
        action="store_true",
        help="architechture (from turnkey_version) - e.g. 'amd64'",
    )
    output.add_argument(
        "-a",
        "--all",
        action="store_true",
        help="Space separated name, version, codename & arch (same as -ntcr)",
    )
    output.add_argument(
        "-j",
        "--json",
        action="store_true",
        help="output all values as json string - conflicts with other output"
        " options format options",
    )
    additional_output = parser.add_argument_group(
        "Additional output options",
        description="Return additional values. Will be only output if no other"
        " options given - otherwise appended to other output.",
    )
    additional_output.add_argument(
        "-d",
        "--debian-codename",
        action="store_true",
        help="Debian codename (from system/chroot)",
    )
    args = parser.parse_args()
    if args.name or args.tklversion or args.codename or args.arch:
        output_values = True
    else:
        output_values = False
    if args.all and output_values:
        parser.error(
            "-a|--all and -n|--name / -t|--tklversion / -c|--codename"
            " / -r|--arch are mutually exclusive.",
        )
    if args.json and (args.all or output_values):
        parser.error("-j|--json conflicts with other output values.")
    if args.string:
        print("STRING")
        turnkey_version = args.string
        rootfs = ""
    else:
        # ensure that args.file is relative to args.rootfs
        if args.file:
            rootfs = ""
            v_file = os.path.abspath(args.file)
        else:
            rootfs = args.rootfs
            v_file = _TKL_VER

        turnkey_version = sysversion.get_turnkey_version(rootfs, v_file)
    if not turnkey_version:
        fatal(
            "can't detect turnkey version - missing or invalid file"
            f"'{os.path.join(rootfs, v_file)}'",
        )

    tkl_appver = []
    tkl_appver_cls = sysversion.AppVer(turnkey_version, rootfs=rootfs)
    if args.all:
        args.name = True
        args.tklversion = True
        args.codename = True
        args.arch = True
    if args.name:
        tkl_appver.append(tkl_appver_cls.appname)
    if args.tklversion:
        tkl_appver.append(tkl_appver_cls.tklver)
    if args.codename:
        tkl_appver.append(tkl_appver_cls.codename)
    if args.arch:
        tkl_appver.append(tkl_appver_cls.arch)
    if args.debian_codename:
        tkl_appver.append(tkl_appver_cls.deb_codename)
    if args.json:
        print(
            json.dumps(
                tkl_appver_cls.app_json(deb_ver=args.debian_codename),
                indent=2,
            ),
        )
    elif tkl_appver:
        print(" ".join(tkl_appver))
    else:
        print(turnkey_version)


if __name__ == "__main__":
    main()
